version: 2
updates:
  # Enable version updates for Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "douglaz"
    labels:
      - "dependencies"
      - "rust"
    groups:
      # Group all non-major updates together
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Add any dependencies you want to ignore here
      # Example:
      # - dependency-name: "some-crate"
      #   versions: [">1.0.0"]
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "douglaz"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      include: "scope"