# Configuration for cargo-deny
# More detailed docs can be found at https://embarkstudios.github.io/cargo-deny/

[graph]
# When creating the dependency graph used as the source of truth when checks are
# executed, this field can be used to prune crates from the graph, removing them
# from the view of cargo-deny
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore
ignore = [
    # instant is unmaintained but only used by backoff crate for tokio feature
    # This is not a security vulnerability, just an unmaintained crate
    "RUSTSEC-2024-0384",
]

[licenses]
# The confidence threshold for detecting licenses from license text
confidence-threshold = 0.8
# List of allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0",
    "Unlicense",
]

# Exceptions for specific crates
exceptions = [
    # Example:
    # { allow = ["GPL-3.0"], name = "some-crate", version = "*" },
]

[[licenses.clarify]]
# Ring has a complicated license situation
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Skip certain crates when checking for duplicates
skip = [
    # Example:
    # { name = "ansi_term", version = "=0.11.0" },
]
# Similarly named crates that are allowed to coexist
allow = [
    # Example:
    # { name = "num-traits", version = "0.1" },
]

# Certain crates/versions that will be skipped when doing duplicate detection
skip-tree = [
    # Example:
    # { name = "windows-sys", version = "0.42" },
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list is detected
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not in the allow list is detected  
unknown-git = "warn"
# List of allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of allowed Git repositories
allow-git = []