name: Integration Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:  # Allow manual triggering
  schedule:
    # Run daily at 2 AM UTC to catch any Twitter API changes
    - cron: '0 2 * * *'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    # Only run if we have Twitter credentials (not on forks)
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.repository == 'douglaz/nostrweet') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build nostrweet binary
        run: nix develop -c cargo build -p nostrweet

      - name: Build integration test binary
        run: nix develop -c cargo build -p nostrweet-integration-tests

      - name: Run integration tests
        run: |
          # The integration tests require TWITTER_BEARER_TOKEN to be set
          # This will be passed via environment variable to the test CLI
          nix develop -c just integration-test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: |
            target/debug/deps/*.log
            /tmp/nostrweet-integration-*

  integration-tests-matrix:
    name: Integration Tests - Extended
    runs-on: ubuntu-latest
    # Only run on schedule or manual trigger for extended testing
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    strategy:
      matrix:
        test: [tweet_fetch, profile, daemon, nostr_post, user_tweets, batch_post, cache_management, utils_query]
      fail-fast: false  # Continue running other tests if one fails
    
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build binaries
        run: |
          nix develop -c cargo build -p nostrweet
          nix develop -c cargo build -p nostrweet-integration-tests

      - name: Run ${{ matrix.test }} test
        run: |
          nix develop -c ./target/debug/nostrweet-integration-tests \
            --twitter-token "$TWITTER_BEARER_TOKEN" \
            run --test ${{ matrix.test }}

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-${{ matrix.test }}
          path: |
            target/debug/deps/*.log
            /tmp/nostrweet-integration-*

  # Summary job to check all integration tests passed
  integration-tests-summary:
    name: Integration Tests Summary
    runs-on: ubuntu-latest
    needs: [integration-tests, integration-tests-matrix]
    if: always()
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.integration-tests.result }}" == "failure" ] || [ "${{ needs.integration-tests.result }}" == "cancelled" ]; then
            echo "❌ Basic integration tests failed or were cancelled"
            exit 1
          fi
          
          # Matrix tests are optional (only run on schedule/manual)
          if [ "${{ needs.integration-tests-matrix.result }}" == "failure" ]; then
            echo "⚠️ Extended integration tests failed (non-blocking)"
          fi
          
          echo "✅ Integration tests passed"